In [1]:
import numpy as np

In [2]:
A = np.array([1.0,2,3])
B = np.array([4.,5,6])
print(A)
print('----')
print(B)

[1. 2. 3.]
----
[4. 5. 6.]


In [3]:
C = np.array([[1.,2,3],[4,5,6]])
print(C)

[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
D = np.array([[[1.,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(D)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]


In [6]:
print(np.random.rand(3,2),"\n")
print(np.ones((3,2)),"\n")
print(np.zeros(2),"\n")
print(np.eye(3))

[[0.96636322 0.40735873]
 [0.73535838 0.12923726]
 [0.57657718 0.27851945]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]] 

[0. 0.] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
A + B

array([5., 7., 9.])

In [8]:
A * B

array([ 4., 10., 18.])

In [9]:
print(A.shape,B.shape,C.shape,D.shape)

(3,) (3,) (2, 3) (2, 2, 3)


In [10]:
C.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [12]:
print(C @ A)

[14. 32.]


In [13]:
A.dot(B)

32.0

In [14]:
(A*B).sum()

32.0

In [15]:
A.max()

3.0

In [16]:
C.max()

6.0

In [17]:
C.max(axis=0)

array([4., 5., 6.])

In [18]:
C.max(axis=1)

array([3., 6.])

In [20]:
print(D)
print(D[0,0,0])
print(D[0,1,2])

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
1.0
6.0


In [21]:
D[0,0,0] = 5
print(D)

[[[ 5.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]


In [23]:
print(D[:,0,:])
print(D[:,1,:])

[[5. 2. 3.]
 [7. 8. 9.]]
[[ 4.  5.  6.]
 [10. 11. 12.]]


In [24]:
print(D[:,:,:])

[[[ 5.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]


In [25]:
print(D[0,1,:])

[4. 5. 6.]


In [26]:
D[0,1,:] = 20
print(D)

[[[ 5.  2.  3.]
  [20. 20. 20.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]


In [27]:
D%2==0

array([[[False,  True, False],
        [ True,  True,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [28]:
D[D%2==0]

array([ 2., 20., 20., 20.,  8., 10., 12.])

In [29]:
D[D%2==0] = 0
print(D)

[[[ 5.  0.  3.]
  [ 0.  0.  0.]]

 [[ 7.  0.  9.]
  [ 0. 11.  0.]]]


In [30]:
print(D.shape)
Dtrans = np.transpose(D,axes=(2,0,1))
print(Dtrans.shape)
print(Dtrans)

(2, 2, 3)
(3, 2, 2)
[[[ 5.  0.]
  [ 7.  0.]]

 [[ 0.  0.]
  [ 0. 11.]]

 [[ 3.  0.]
  [ 9.  0.]]]


In [31]:
X = np.reshape(np.linspace(0,11,12),(3,4))
Y = np.reshape(np.linspace(-11,0,12),(3,4))
print(X)
print(Y)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[-11. -10.  -9.  -8.]
 [ -7.  -6.  -5.  -4.]
 [ -3.  -2.  -1.   0.]]


In [32]:
print(X.shape)
print(Y.shape)
X+Y

(3, 4)
(3, 4)


array([[-11.,  -9.,  -7.,  -5.],
       [ -3.,  -1.,   1.,   3.],
       [  5.,   7.,   9.,  11.]])

In [33]:
Z = np.reshape(np.linspace(0,5,6),(2,3))
print(Z)

[[0. 1. 2.]
 [3. 4. 5.]]


In [34]:
print(X.shape)
print(Z.shape)
X+Z

(3, 4)
(2, 3)


ValueError: operands could not be broadcast together with shapes (3,4) (2,3) 

In [35]:
W = np.linspace(10,13,4)
print(W)

[10. 11. 12. 13.]


In [36]:
print(X.shape)
print(X)
print(W.shape)
print(W)
X+W

(3, 4)
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
(4,)
[10. 11. 12. 13.]


array([[10., 12., 14., 16.],
       [14., 16., 18., 20.],
       [18., 20., 22., 24.]])

In [37]:
U = np.linspace(0,4,3)
print(U)

[0. 2. 4.]


In [38]:
print(X.shape)
print(U.shape)
X+U

(3, 4)
(3,)


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [40]:
Up = U[:,None]
print(Up.shape)
print(Up)

(3, 1)
[[0.]
 [2.]
 [4.]]


In [41]:
print(X.shape)
print(X)
print(Up.shape)
print(Up)
X+Up

(3, 4)
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
(3, 1)
[[0.]
 [2.]
 [4.]]


array([[ 0.,  1.,  2.,  3.],
       [ 6.,  7.,  8.,  9.],
       [12., 13., 14., 15.]])

In [42]:
P1 = np.random.rand(10,2)
P2 = np.random.rand(5,2)

In [43]:
res = np.zeros((10,5))
for i in range(10):
    for j in range(5):
        d = P1[i,:] - P2[j,:]
        res[i,j] = np.sqrt(d.dot(d))
print(res)

[[0.36446695 0.09243477 0.5585799  0.63701043 0.49759526]
 [0.07878183 0.395275   0.52407869 0.33187506 0.19349329]
 [0.60928151 0.25830133 0.50637641 0.83967654 0.70472631]
 [0.8356405  0.9307053  0.30759894 0.77727334 0.74773007]
 [0.6121978  0.77506394 0.21510741 0.54726856 0.51583352]
 [0.23800644 0.68328951 0.73802911 0.17034355 0.1843949 ]
 [0.55677346 0.50878235 0.12944455 0.65737773 0.55609045]
 [1.04730642 0.77179696 0.61558424 1.1987464  1.08666793]
 [0.97955923 0.74035711 0.51999441 1.11547035 1.00802412]
 [0.48906409 0.04076403 0.64197251 0.76708143 0.62783802]]


In [45]:
diff = P1[:,None,:] - P2[None,:,:]
print(diff.shape)

(10, 5, 2)


In [46]:
np.sqrt((diff*diff).sum(axis=2))

array([[0.36446695, 0.09243477, 0.5585799 , 0.63701043, 0.49759526],
       [0.07878183, 0.395275  , 0.52407869, 0.33187506, 0.19349329],
       [0.60928151, 0.25830133, 0.50637641, 0.83967654, 0.70472631],
       [0.8356405 , 0.9307053 , 0.30759894, 0.77727334, 0.74773007],
       [0.6121978 , 0.77506394, 0.21510741, 0.54726856, 0.51583352],
       [0.23800644, 0.68328951, 0.73802911, 0.17034355, 0.1843949 ],
       [0.55677346, 0.50878235, 0.12944455, 0.65737773, 0.55609045],
       [1.04730642, 0.77179696, 0.61558424, 1.1987464 , 1.08666793],
       [0.97955923, 0.74035711, 0.51999441, 1.11547035, 1.00802412],
       [0.48906409, 0.04076403, 0.64197251, 0.76708143, 0.62783802]])